#
# ~/.bash_aliases
#

alias sudo='sudo '
alias cls='echo -ne "\033c"'
alias yis='yi -s -t zh'
alias py='python2'
alias py2='python2'
alias py3='python3'
alias l='ls -F --color=auto'
alias la='l -Ah'
alias ll='l -Ahl'
alias grep='grep --color=auto'
alias mkdir='mkdir -pv'
alias du1='du -d1 -h'
alias date1='date "+%Y-%m-%d_%H-%M-%S_%a"'
alias date2='date "+%H:%M:%S"'
alias bc='bc -ql'
alias lsblk='lsblk -o NAME,LABEL,SIZE,TYPE,FSTYPE,MOUNTPOINT'
alias startx='startx ~/.xinitrc'
alias sshd='pidof sshd && systemctl stop sshd || systemctl start sshd'
alias vcat='vimcat'
alias inotify='inotifywait -mrq --timefmt %F_%T --format "%T %w %e %f" -e modify,delete,create,attrib,move'
alias inotify-ao='inotifywait -mrq --timefmt %F_%T --format "%T %w %e %f" -e access,open'
alias axel='axel --alternate'
alias ping='ping -c 5'
#alias rm='rm -I'
#alias cp='cp -ir'
#alias mv='mv -i'
#alias ln='ln -i'


# pacman
alias pac='sudo pacman -S'
alias pacy='sudo pacman -Syy'
alias pacu='sudo pacman -Syu'
alias pacr='sudo pacman -Rns'
alias pacs='pacman -Ss'
alias paci='pacman -Si'
alias paclo='pacman -Qdtq'
alias paccc='sudo paccache -rvk 3'
alias paccn='sudo paccache -rvuk 0'
alias paclf='pacman -Ql'
# yaourt
alias yao='yaourt -S'
alias yaoy='sudo yaourt -Syy'
alias yaou='sudo yaourt -Syu'
alias yaor='sudo yaourt -Rns'
alias yaos='yaourt -Ss'
alias yaoi='yaourt -Si'
alias yaolo='yaourt -Qdtq'
alias yaoc='sudo yaourt -Sc'
alias yaolf='yaourt -Ql'


alias cdm='cd /home/wj/windows/'
alias usetips='vless ~/backup/useTips'
alias errors="journalctl --priority=0..3 --catalog -n"
alias uninterruptible='ps -eo pid,args,stat,etime,user | grep -v "grep\|PID COMMAND\|-d\|-D" | grep D'
alias ipaddress='ifconfig | grep broadcast | awk "{print \$2}";curl -s ip.cn | \grep -o "[0-9.]\+"'
alias sitedownload='wget -Erkp -np'
alias acpi='bDir="/sys/class/power_supply/BAT0";[ -e $bDir ] || bDir="/sys/class/power_supply/BAT1";echo $(cat $bDir/status)\ $(cat $bDir/capacity)%;unset bDir'
alias caffeine='xset s off'
alias trA2a='tr [:upper:] [:lower:]'
alias tra2A='tr [:lower:] [:upper:]'
alias ps1='echo -e "\e[01;31m\t `volume`    `backlight`     `acpi`    `date "+%F_%a %T"`\n\e[00;36m `pwd`\e[m "'
alias pkgfile='pkgfile -v'
alias load='uptime | cut -d, -f3- | cut -d" " -f5-'
alias snapperlist='for name in `ls /etc/snapper/configs/`; do separatedLine 1;snapper --iso -c $name list;done'
